version: "3.9"
services:
  db:
    image: postgres:14-alpine
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: "${TYPEORM_PASSWORD}"
      POSTGRES_USER: "${TYPEORM_USERNAME}"
      POSTGRES_DB: "${TYPEORM_DATABASE}"
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
